version: '3.8'

services:
  postgress: 
    image:postgres:15
    container_name:postgres_db
    environment:
      POSTGRES_USER: harshika
      POSTGRES_PASSWORD: harshika123456
      POSTGRES_DB: school
    ports: 
        -'5432:5432'
    
app:
  container_name: nextjs_app
  ports:
    -'3000:3000'
  environment:
    - DATABASE_URL: postgresql://harshika:harshika123456@localhost:5432/school
  depends_on:
    -postgres